//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVCProject.Models.Entity
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Sale
    {
        public int SaleID { get; set; }
        public Nullable<int> Item { get; set; }
        public Nullable<int> Customer { get; set; }
        public Nullable<byte> Number { get; set; }
        public Nullable<decimal> Price { get; set; }
    
        public virtual Customer Customer1 { get; set; }
        public virtual Item Item1 { get; set; }
    }
}
